### ISSUE TITLE
Problem with installing requirements

### ISSUE THREAD

**Issue by Thomaswbt** [samuelstanton/lambo#7]
Hi!
I have an issue installing the required version of gpytorch and botorch. I cannot fetch the specific commit hash. Could you please check if this is a common problem or this is a problem of my network? If I skip this step and install gpytorch and botorch directly form pip, I found that I would encounter problems similar to #3 and #4 and I cannot trivially fix them. So I wonder the versions of gpytorch and botorch may matter. Thanks in advance!

<img width="1318" alt="屏幕快照 2022-10-19 下午10 45 37" src="https://user-images.githubusercontent.com/55548313/196724770-9105eec8-caf5-4b2e-8f34-2d7a6b657556.png">
<img width="1068" alt="屏幕快照 2022-10-19 下午10 46 04" src="https://user-images.githubusercontent.com/55548313/196724781-e54252f7-b497-49d1-bee2-1f0ffcb4c1f1.png">

**Comment by samuelstanton** [comment]
Hi thanks for creating the issue and sorry to hear you're having trouble. Unfortunately this package is quite sensitive to which version of `gpytorch` and `botorch` is used, which is why I pinned the requirements to those specific commit hashes. I'm not sure why you're having trouble fetching those commit hashes... would you mind seeing if you can clone the repo and check out those commits manually? In the short term this is the fastest way to get the code running.

The long-term fix is to update the requirements to stable releases of GPyTorch/BoTorch, however you are correct that it leads to non-trivial bugs that are likely caused by GPyTorch itself and which will require opening another issue there.

**Comment by samuelstanton** [comment]
are you using IPv6 by any chance?

https://stackoverflow.com/questions/51635536/the-tls-connection-was-non-properly-terminated

**Comment by Thomaswbt** [comment]
Thank you! I tried to manually install the specific commit hashes and most errors vanished consequently! However the numerical stability issue mentioned in #3 and still exists and it causes error in validating the correlation matrix. I think I shall move to #3 if I cannot solve it trivially. I will close this issue.
